name: multiuser_habits
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.4.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^3.6.0
  cloud_firestore: ^5.4.3
  provider: ^6.0.0
  firebase_auth: ^5.0.0 
  google_fonts: ^6.2.0
  path_provider: ^2.1.4
  timeago: ^3.7.0


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
